name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        electron_version: ["28.0.0", "27.0.0"]  # 支持多个 Electron 版本
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build for Electron
        run: |
          npm run build -- \
            --platform=${{ runner.os == 'Windows' ? 'win32' : (runner.os == 'macOS' ? 'darwin' : 'linux') }} \
            --arch=x64 \
            --runtime=electron \
            --runtime-version=${{ matrix.electron_version }}
      - name: Upload prebuilds
        uses: actions/upload-artifact@v3
        with:
          name: prebuild-${{ runner.os }}-electron-${{ matrix.electron_version }}
          path: ./build/
